apiVersion: plural.sh/v1alpha1
kind: Dependencies
metadata:
  description: postgres equinix setup 
  version: 0.1.2
spec:
  dependencies:
  - name: equinix-bootstrap
    repo: bootstrap
    type: terraform
    version: '>= 0.1.1'
  providers:
  - equinix
  outputs:
    access_key_id: access_key_id
    secret_access_key: secret_access_key
