apiVersion: v1
kind: Secret
metadata:
  name: {{ include "directus-plural.secretName" . }}
  labels:
{{ include "directus-plural.labels" . | indent 4 }}
stringData:
  key: {{ .Values.directus.key }}
  secret: {{ .Values.directus.secret }}
  adminEmail: {{ .Values.directus.admin.email }}
  adminPassword: {{ .Values.directus.admin.password }}
  {{- if .Values.directus.oidc.enabled }}
  oidcIssuer: {{ .Values.directus.oidc.issuer }}
  oidcClientId: {{ .Values.directus.oidc.clientId }}
  oidcClientSecret: {{ .Values.directus.oidc.clientSecret }}
  {{- end }}